[package]
name = "cli"
version = "0.1.0"
edition = "2021"
#authors = "boolsatellite < boolsatellite@gmail.com"



[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
serde = { version = "1.0.209", features = ["derive"] }
csv = "1.3.0"
anyhow = "1.0.86"
serde_json = "1.0.128"
